"""Real-time behavioral detection for Noema.

This package owns the near-real-time time scale, kept strictly separate
from the 20-minute semantic classification pipeline:

raw/session state
→ rolling behavioral features (:mod:`features`)
→ deterministic local candidate detector (:mod:`detector`)
→ fast model verification (compact feature summary only)
→ intervention policy
→ outcome observation

Nothing here classifies raw ActivityWatch rows, and nothing here writes
semantic classifications. AFK is always an operational state, never a
productivity verdict.
"""

from .detector import (
    CandidateDecision,
    DetectionState,
    DetectionTracker,
    DetectorConfig,
    DistractionCandidateDetector,
)
from .features import BehaviorWindow, BehaviorWindowConfig, build_behavior_windows
from .records import DetectionRecord, detection_id
from .reasoning import (
    REASONING_VERSION,
    RESPONSE_CHARACTER,
    RESPONSE_CHALLENGE,
    RESPONSE_CLASSES,
    RESPONSE_ENCOURAGEMENT,
    RESPONSE_GENTLE,
    RESPONSE_MEME,
    RESPONSE_NONE,
    RESPONSE_SARCASTIC,
    RESPONSE_STICKER,
    STATE_DISTRACTED,
    STATE_INTENTIONAL_BREAK,
    STATE_NOT_DISTRACTED,
    STATE_UNCERTAIN,
    REASONING_STATES,
    ReasoningResult,
    build_reasoning_context,
    build_reasoning_prompt,
    uncertain_result,
    validate_reasoning_payload,
)
from .intervention import (
    CLASS_BREAK,
    CLASS_CHALLENGE,
    CLASS_ENCOURAGEMENT,
    CLASS_MEME,
    CLASS_NONE,
    CLASS_NUDGE,
    CLASS_QUIRK,
    CLASS_REMINDER,
    DELIVERY_BROWSER,
    DELIVERY_DASHBOARD,
    DELIVERY_NONE,
    DELIVERY_OVERLAY,
    DELIVERY_TOAST,
    INTERVENTION_BREAK_SUGGESTION,
    INTERVENTION_MEME_NUDGE,
    INTERVENTION_NONE,
    INTERVENTION_NOTIFICATION,
    INTERVENTION_REASONING_VERSION,
    INTERVENTION_RESPONSE_CLASSES,
    INTERVENTION_TONES,
    INTERVENTION_TYPES,
    RESPONSE_CLASS_TO_SELECTOR_CLASS,
    TONE_CALM,
    TONE_DIRECT,
    TONE_ENCOURAGING,
    TONE_NEUTRAL,
    TONE_PLAYFUL,
    TONE_SARCASTIC_LIGHT,
    TONE_TO_RESPONSE_TONE,
    TONE_URGENT,
    InterventionDecision,
    InterventionReasoner,
    build_intervention_history,
    build_intervention_prompt,
    declined_result,
    validate_intervention_payload,
)
from .verifier import FastModelVerifier, VerificationConfig, VerificationResult

__all__ = [
    "BehaviorWindow",
    "BehaviorWindowConfig",
    "CLASS_BREAK",
    "CLASS_CHALLENGE",
    "CLASS_ENCOURAGEMENT",
    "CLASS_MEME",
    "CLASS_NONE",
    "CLASS_NUDGE",
    "CLASS_QUIRK",
    "CLASS_REMINDER",
    "CandidateDecision",
    "DELIVERY_BROWSER",
    "DELIVERY_DASHBOARD",
    "DELIVERY_NONE",
    "DELIVERY_OVERLAY",
    "DELIVERY_TOAST",
    "DetectionRecord",
    "DetectionState",
    "DetectionTracker",
    "DetectorConfig",
    "DistractionCandidateDetector",
    "FastModelVerifier",
    "INTERVENTION_BREAK_SUGGESTION",
    "INTERVENTION_MEME_NUDGE",
    "INTERVENTION_NONE",
    "INTERVENTION_NOTIFICATION",
    "INTERVENTION_REASONING_VERSION",
    "INTERVENTION_RESPONSE_CLASSES",
    "INTERVENTION_TONES",
    "INTERVENTION_TYPES",
    "REASONING_STATES",
    "REASONING_VERSION",
    "RESPONSE_CHARACTER",
    "RESPONSE_CHALLENGE",
    "RESPONSE_CLASSES",
    "RESPONSE_CLASS_TO_SELECTOR_CLASS",
    "RESPONSE_ENCOURAGEMENT",
    "RESPONSE_GENTLE",
    "RESPONSE_MEME",
    "RESPONSE_NONE",
    "RESPONSE_SARCASTIC",
    "RESPONSE_STICKER",
    "STATE_DISTRACTED",
    "STATE_INTENTIONAL_BREAK",
    "STATE_NOT_DISTRACTED",
    "STATE_UNCERTAIN",
    "TONE_CALM",
    "TONE_DIRECT",
    "TONE_ENCOURAGING",
    "TONE_NEUTRAL",
    "TONE_PLAYFUL",
    "TONE_SARCASTIC_LIGHT",
    "TONE_TO_RESPONSE_TONE",
    "TONE_URGENT",
    "InterventionDecision",
    "InterventionReasoner",
    "ReasoningResult",
    "VerificationConfig",
    "VerificationResult",
    "build_behavior_windows",
    "build_intervention_history",
    "build_intervention_prompt",
    "build_reasoning_context",
    "build_reasoning_prompt",
    "declined_result",
    "detection_id",
    "uncertain_result",
    "validate_intervention_payload",
    "validate_reasoning_payload",
]
